routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

// Route::get('/', function () {
//     return view('welcome');
// });
Route::namespace('Web\brand')->group(function () {
    Route::get('brand/login', ['as' => 'brandlogin', 'uses' => 'UserController@login']);
    Route::get('brand/forgot-password', ['as' => 'forgotpassword', 'uses' => 'UserController@forgotPassword']);
});

Route::namespace('Web\corporate')->group(function () {
    Route::get('corporate/login', ['as' => 'corporatelogin', 'uses' => 'UserController@login']);
    Route::get('corporate/forgot-password', ['as' => 'corporateforgotpassword', 'uses' => 'UserController@forgotPassword']);
});
Route::namespace('Web\corporate')->middleware('CheckSessionCorporate')->prefix('corporate')->group(function () {

    Route::get('dashboard', ['as' => 'corporatedashboard', 'uses' => 'DashboardController@index']);
    Route::get('perksvilla', ['as' => 'perksvilla', 'uses' => 'RewardController@index']);
    Route::get('orderhistory', ['as' => 'corporateorderhistory', 'uses' => 'RewardController@orderHistory']);
    Route::prefix('profile')->group(function () {
        Route::get('edit', ['as' => 'corporateeditprofile', 'uses' => 'UserController@editProfile']);
        Route::get('view', ['as' => 'corporateviewprofile', 'uses' => 'UserController@viewProfile']);
        Route::get('changepassword', ['as' => 'corporatechangepassword', 'uses' => 'UserController@changePassword']);
    });
    Route::prefix('employee')->group(function () {
        Route::get('/', ['as' => 'employee', 'uses' => 'EmployeeController@employee']);
        Route::get('add', ['as' => 'addemployee', 'uses' => 'EmployeeController@addEmployee']);
    });
    Route::prefix('reward')->group(function () {
        Route::get('/', ['as' => 'reward', 'uses' => 'RewardController@reward']);
        Route::get('add', ['as' => 'addreward', 'uses' => 'RewardController@addReward']);
        Route::get('success', ['uses' => 'RewardController@success', 'as' => 'reward.success']);
        Route::post('fail', ['uses' => 'RewardController@fail', 'as' => 'reward.fail']);
    });
    /*  Support  */
    Route::group(["prefix" => "message"], function () {
        Route::get('/', ['uses' => 'SupportController@index', 'as' => "corporate.support"]);
        Route::get('add', ['uses' => 'SupportController@getManage', 'as' => "corporate.support.manage"]);
        Route::get('reply/{id?}', ['uses' => 'SupportController@replyShow', 'as' => "corporate.support.reply"]);
        Route::get('delete/{id}', ['uses' => 'SupportController@delete', 'as' => "corporate.support.delete"]);
        Route::get('lists', ['uses' => 'SupportController@lists', 'as' => "corporate.support.lists"]);
        Route::post('save', ['uses' => 'SupportController@save', 'as' => "corporate.support.save"]);
        Route::post('reply/save', ['uses' => 'SupportController@replySave', 'as' => "corporate.support.reply.save"]);
        Route::get('count', ['uses' => 'SupportController@supportMessageCount', 'as' => "corporate.support.count"]);
    });

    Route::post('notification', ['as' => 'corporate.notification', 'uses' => 'UserController@notification']);
    Route::post('notification/read', ['as' => 'corporate.notification.read', 'uses' => 'UserController@notificationRead']);
});

Route::namespace('Web\brand')->middleware('CheckSessionBrand')->prefix('brand')->group(function () {

    Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    Route::get('coupon', ['as' => 'coupon', 'uses' => 'CouponController@index']);
    Route::get('orderhistory', ['as' => 'orderhistory', 'uses' => 'OrderHistoryController@index']);
    Route::post('notification', ['as' => 'brand.notification', 'uses' => 'UserController@notification']);
    Route::post('notification/read', ['as' => 'brand.notification.read', 'uses' => 'UserController@notificationRead']);

    Route::get('wallet', ['as' => 'brandwallet', 'uses' => 'UserController@myWallet']);

    Route::prefix('offer')->group(function () {
        Route::get('/', ['as' => 'brandoffer', 'uses' => 'OfferController@index']);
        Route::get('add', ['as' => 'addoffer', 'uses' => 'OfferController@addOffer']);
        Route::get('past', ['as' => 'pastoffer', 'uses' => 'OfferController@pastOffer']);
    });

    Route::prefix('profile')->group(function () {
        Route::get('edit', ['as' => 'editprofile', 'uses' => 'UserController@editProfile']);
        Route::get('view', ['as' => 'viewprofile', 'uses' => 'UserController@viewProfile']);
        Route::get('changepassword', ['as' => 'changepassword', 'uses' => 'UserController@changePassword']);
        Route::get('wallet', ['as' => 'wallet', 'uses' => 'UserController@myWallet']);
        Route::get('bankdetails', ['as' => 'bankdetails', 'uses' => 'UserController@bankDetails']);
    });
    /*  Support  */
    Route::group(["prefix" => "message"], function () {
        Route::get('/', ['uses' => 'SupportController@index', 'as' => "brand.support"]);
        Route::get('add', ['uses' => 'SupportController@getManage', 'as' => "brand.support.manage"]);
        Route::get('reply/{id?}', ['uses' => 'SupportController@replyShow', 'as' => "brand.support.reply"]);
        Route::get('delete/{id}', ['uses' => 'SupportController@delete', 'as' => "brand.support.delete"]);
        Route::get('lists', ['uses' => 'SupportController@lists', 'as' => "brand.support.lists"]);
        Route::post('save', ['uses' => 'SupportController@save', 'as' => "brand.support.save"]);
        Route::post('reply/save', ['uses' => 'SupportController@replySave', 'as' => "brand.support.reply.save"]);
        Route::get('count', ['uses' => 'SupportController@supportMessageCount', 'as' => "brand.support.count"]);
    });
});

Route::namespace('Web\admin')->group(function () {
    Route::get('backoffice/login',['as' => 'adminlogin', 'uses' => 'UserController@login']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'UserController@logout']);
    Route::post('setsession', 'UserController@setSession');
});

Route::namespace('Web\admin')->middleware('CheckSession')->prefix('admin')->group(function () {
    Route::prefix('category')->group(function () {
        Route::get('brand', ['as' => 'brandcategory', 'uses' => 'CategoryController@brand']);
        Route::get('corporate', ['as' => 'employeecategory', 'uses' => 'CategoryController@employee']);
        Route::get('reward', ['as' => 'rewardcategory', 'uses' => 'CategoryController@reward']);
    });
    Route::prefix('location')->group(function () {
        Route::get('country', ['as' => 'country', 'uses' => 'LocationController@country']);
        Route::get('state', ['as' => 'state', 'uses' => 'LocationController@state']);
        Route::get('city', ['as' => 'city', 'uses' => 'LocationController@city']);
    });
    Route::prefix('brand')->group(function () {
        Route::get('add', ['as' => 'brandadd', 'uses' => 'BrandController@addBrand']);
        Route::get('list', ['as' => 'brandlist', 'uses' => 'BrandController@listBrand']);
        Route::get('payment/request', ['as' => 'brandpayment', 'uses' => 'BrandController@paymentRequestBrand']);
    });
    Route::prefix('corporate')->group(function () {
        Route::get('list', ['as' => 'corporatelist', 'uses' => 'CorporateController@listCorporate']);
        Route::get('add', ['as' => 'corporateadd', 'uses' => 'CorporateController@addCorporate']);
        Route::get('order/history', ['as' => 'orderhistorycorporate', 'uses' => 'CorporateController@orderHistoryCorporate']);
    });
    Route::prefix('reward')->group(function () {
        Route::get('/', ['as' => 'generalreward', 'uses' => 'RewardController@getRewards']);
        Route::get('usercreated', ['as' => 'usercreatedreward', 'uses' => 'RewardController@getRewards']);
    });
    Route::prefix('offer')->group(function () {
        Route::get('pending', ['as' => 'offerpending', 'uses' => 'OfferController@offer']);
        Route::get('active', ['as' => 'offeractive', 'uses' => 'OfferController@offer']);
        Route::get('upcoming', ['as' => 'offerupcoming', 'uses' => 'OfferController@offer']);
        Route::get('past', ['as' => 'offerpast', 'uses' => 'OfferController@offer']);
        Route::get('reject', ['as' => 'offerreject', 'uses' => 'OfferController@offer']);
    });
    Route::prefix('coupon')->group(function () {
        Route::get('active', ['as' => 'activecoupon', 'uses' => 'CouponController@coupon']);
        Route::get('used', ['as' => 'usedoupon', 'uses' => 'CouponController@coupon']);
        Route::get('expired', ['as' => 'expiredcoupon', 'uses' => 'CouponController@coupon']);
    });
    Route::prefix('sms-templates')->group(function () {
        Route::get('/', ['as' => 'sms.templates', 'uses' => 'SMSTemplateController@index']);
        Route::get('add', ['as' => 'sms.templates.add', 'uses' => 'SMSTemplateController@index']);
    });
    Route::get('employee', ['as' => 'employeeadmin', 'uses' => 'EmployeeController@employee']);
    Route::get('dashboard', ['as' => 'admindashboard', 'uses' => 'DashboardController@index']);
    /*  mail template   */
    Route::prefix('profile')->group(function () {
        Route::get('edit', ['as' => 'adminprofile', 'uses' => 'UserController@editProfile']);
        Route::get('changepassword', ['as' => 'adminchangepassword', 'uses' => 'UserController@changePassword']);
    });
    Route::group(['prefix' => 'mailtemplates'], function () {

        Route::get('/', ['uses' => 'MailtemplateController@index', 'as' => 'admin.mailtemplates.index']);

app/Http/Controllers/Api/admin/AdminController.php
<?php
namespace App\Http\Controllers\Api\admin;

use App\Http\Controllers\Controller;
use Request;
use Validator;
use Carbon\Carbon;
use App\Http\Models\User;
use App\Http\Models\Corporate;
use App\Http\Models\Reward;
use App\Http\Models\Brand;
use App\Http\Models\Employee;
use App\Http\Models\Offer;
use App\Http\Models\Support;


class AdminController extends Controller
{
	public function __construct(){
		  $this->corporate = new Corporate;
          $this->user = new User;
          $this->reward = new Reward;
          $this->employee = new Employee;
          $this->brand = new Brand;
          $this->offer = new Offer;
		  $this->support = new Support;
    }
    public function getStatistics(){
       try{
            $use = array();
            $unuse = array();
            $employee = array();
    
            $unuse['redeem'] =  0;
            $use['redeem'] =1;
            $employee['status'] = 1;  
            $data = array(
                'active_employee'        => $this->employee->getEmployeeCount($employee),
                'active_brand'           => $this->brand->getBrandCount(array('status'=>1)),
                'active_corporate'       => $this->corporate->getActiveCorporateCount(),
                'active_offers'          => $this->offer->offerCount(array('status'=>1)),
                'pending_offers'         => $this->offer->offerCount(array('status'=>3)),
                'upcoming_offers'        => $this->offer->offerCount(array('status'=>2)),
                'today_order'            => $this->offer->getTodayOrders(),
                'today_redeem'           => $this->offer->getTodayRedeem(array()),
                'total_sales'            => $this->offer->getSales(array()),
                'open_tickets'           => $this->support->ticketCount(array('status'=>1)),
                'closed_tickets'         => $this->support->ticketCount(array('status'=>2)),
                'payment_request'        => $this->brand->paymentRequestCount(),
            );
            if(!empty($data)){
                return response()->json([
                    'error'   => false,
                    'data' =>$data,
                ],200);
            } else{
                return response()->json([
                    'error'   => true,
                    'message' =>"Something went Wrong",
                ],500);
            }   
        } catch(\Exception $e) {
            return response()->json([
                    'error'   => true,
                    'message' => $e->getMessage(),
                ],500);
        } catch(\QueryException $e) {
            return response()->json([
                    'error'   => true,
                    'message' => $e->getMessage(),
                ],500);
        } 
    }
}

resources/views/admin/dashboard.blade.php
@extends('admin.master')
@section('content')
	<div class="wraper container-fluid">
		<div class="row">
            <div class="col-md-4">
                <div class="mini-stat clearfix">
                    <span class="mini-stat-icon bg-pink"><i class="fa fa-tag"></i></span>
                    <div class="mini-stat-info text-right">
                        <a href="{{route('offerpending')}}"><span class="" data-bind="text:pending_offers"></span></a>
                        <span style="font-size: 19px;">Pending Offers</span>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="mini-stat clearfix">
                    <span class="mini-stat-icon bg-success"><i class="fa fa-tag"></i></span>
                    <div class="mini-stat-info text-right">
                        <a href="{{route('offeractive')}}"><span class="" data-bind="text:active_offers"></span></a>
                         <span style="font-size: 19px;">Active Offers</span>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="mini-stat clearfix">
                    <span class="mini-stat-icon bg-warning"><i class="fa fa-tag"></i></span>
                    <div class="mini-stat-info text-right">
                        <a href="{{route('offerupcoming')}}"><span class="" data-bind="text:upcoming_offers"></span></a>
                         <span style="font-size: 19px;">Upcoming Offers</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
        	<div class="col-md-4">
                <div class="mini-stat clearfix">
                    <span class="mini-stat-icon bg-success"><i class="fa fa-shopping-cart"></i></span>
                    <div class="mini-stat-info text-right">
                        <a href="{{route('orderhistorycorporate')}}"><span class="" data-bind="text:today_order"></span></a>
                        <span style="font-size: 19px;">Today's Order</span>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="mini-stat clearfix">
                    <span class="mini-stat-icon bg-warning"><i class="fa fa-gift"></i></span>
                    <div class="mini-stat-info text-right">
                        <span class="" data-bind="text:today_redeem"></span>
                        <span style="font-size: 19px;">Today's Redeem</span>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="mini-stat clearfix">
                    <span class="mini-stat-icon bg-pink"><i class="fa fa-usd"></i></span>
                    <div class="mini-stat-info text-right">
                        <a href="{{route('orderhistorycorporate')}}"><span class="" data-bind="text:total_sales"></span></a>
                        <span style="font-size: 19px;">Total Sales</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="mini-stat clearfix">
                    <span class="mini-stat-icon bg-success"><i class="fa fa-credit-card"></i></span>
                    <div class="mini-stat-info text-right">
                        <a href="{{route('brandpayment')}}"><span class="" data-bind="text:payment_request"></span></a>
                        <span style="font-size: 19px;">Payment Request</span>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="mini-stat clearfix">
                    <span class="mini-stat-icon bg-pink"><i class="fa fa-ticket"></i></span>
                    <div class="mini-stat-info text-right">
                        <a href="{{route('support.open')}}"><span class=""  data-bind="text:open_tickets"></span></a>
                        <span style="font-size: 19px;">Open Tickets</span>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="mini-stat clearfix">
                    <span class="mini-stat-icon bg-success"><i class="fa fa-ticket"></i></span>
                    <div class="mini-stat-info text-right">
                        <a href="{{route('support.closed')}}"><span class="" data-bind="text:closed_tickets"></span></a>
                        <span style="font-size: 19px;">Closed Tickets</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="mini-stat clearfix">
                    <span class="mini-stat-icon bg-info"><i class="ion-flask"></i></span>
                    <div class="mini-stat-info text-right">
                        <a href="{{route('brandlist')}}"><span class="" data-bind="text:active_brand"></span></a>
                        <span style="font-size: 19px;">Active Brands</span>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="mini-stat clearfix">
                    <span class="mini-stat-icon bg-warning"><i class="fa fa-building-o"></i></span>
                    <div class="mini-stat-info text-right">
                        <a href="{{route('corporatelist')}}"><span class="" data-bind="text:active_corporate"></span></a>
                        <span style="font-size: 19px;">Active Corporates</span>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="mini-stat clearfix">
                    <span class="mini-stat-icon bg-pink"><i class="ion-person"></i></span>
                    <div class="mini-stat-info text-right">
                        <a href="{{route('employeeadmin')}}"><span class="" data-bind="text:active_employee"></span></a>
                        <span style="font-size: 19px;">Active Employees</span>
                    </div>
                </div>
            </div>
        </div>
	</div>
	@section('script')
		<script type="text/javascript">
			var id = "{{ Session::get('id')}}";
			var token = "{{ Session::get('token')}}";
            var statisticsApi = "{{config('constant.api.admin.statistics')}}";
        </script>
		<script type="text/javascript" src="{{config('constant.script.dashboard')}}"></script>
	@endsection
@endsection

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="title" content="{{env("PROJECT_NAME")}}">
        <meta name="author" content="{{env("PROJECT_NAME")}}">
        <title>@yield("title"){{env("PROJECT_NAME")}}</title>
        
        <!-- Google-Fonts -->
        <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:100,300,400,600,700,900,400italic' rel='stylesheet'>

        <!-- Bootstrap core CSS -->
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.bootstrap')}}" />
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.bootstrap-reset')}}" />

        <!--Animation css-->
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.animate')}}" />

        <!--Icon-fonts css-->
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.ionicons')}}" />
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.fontawesome')}}" />

        <!-- Custom styles for this template -->
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.style')}}" />
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.styleresponsive')}}" />
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.helper')}}" />

        <!-- Tostr Notification-->
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.toastr')}}" />
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.sweetalert')}}" />
    </head>
    <body  class="login-bg">
        <div class="wrapper-page animated fadeInDown" id="divLogin">
            <div class="panel panel-color panel-primary">
            <div class="panel-heading"> 
               <h3 class="text-center m-t-10"> Sign In to <strong>PerksVilla</strong> </h3>
            </div> 
            <form id="login_form" class="form-horizontal m-t-40">
                <div class="form-group" >
                    <div class="col-xs-12" data-bind="visible:isError">
                        <h3 class="error" data-bind="text:errorMsg"></h3>
                    </div>
                </div>        
                <div class="form-group ">
                    <div class="col-xs-12">
                        <input class="form-control" name="txtEmail" id="txtEmail" type="text" placeholder="Username">
                    </div>
                </div>
                <div class="form-group ">
                    
                    <div class="col-xs-12">
                        <input class="form-control" name="txtPassword" id="txtPassword" type="password" placeholder="Password">
                    </div>
                </div>

                <div class="form-group ">
                    <div class="col-xs-12">
                        <label class="cr-styled">
                            <input type="checkbox" name="rememberme" value="1" id="txtRemember" checked="checked">
                            <i class="fa"></i> 
                            Remember me
                        </label>
                    </div>
                </div>
                
                <div class="form-group text-right">
                    <div class="col-xs-12">
                        <button class="btn btn-purple w-md" id="btnLogin" data-bind = "click: loginClick" type="button">Log In</button>
                    </div>
                </div>
            </form>
            </div>
        </div>
        <script>
            var baseURL         = "{{url('/').'/'}}";
            var _token          = "{{csrf_token()}}";
            var loginApiPath    = "{{config('constant.api.login')}}";
            var setSessionPath  = "{{config('constant.web.setSession')}}";
            var landingPage    = " {{route('admindashboard')}}";
        </script>
        <script type="text/javascript" src="{{config('admin_constant.script.jquery')}}"></script>
        <script type="text/javascript" src="{{config('admin_constant.script.bootstrap')}}"></script>
        <script type="text/javascript" src="{{config('admin_constant.script.pace')}}"></script>
        <script type="text/javascript" src="{{config('admin_constant.script.wow')}}"></script>
        <script type='text/javascript' src="{{config('admin_constant.script.sweetalert')}}"></script>
        <script type='text/javascript' src="{{config('admin_constant.script.sweetalertinit')}}"></script> 
        <script type="text/javascript" src="{{config('admin_constant.script.nicescroll')}}"></script>
        <script type='text/javascript' src="{{config('admin_constant.script.app')}}"></script>
        <script type="text/javascript" src="{{config('admin_constant.script.knockout')}}"></script>
        <script type="text/javascript" src="{{config('admin_constant.script.toastr')}}"></script>
        <script type="text/javascript" src="{{config('constant.script.common.helper')}}"></script>
        <script type="text/javascript" src="{{config('brand_constant.script.validate')}}"></script>
        <script type="text/javascript" src="{{config('constant.script.common.jquerymd5')}}"></script>
        <script type="text/javascript" src="{{config('admin_constant.script.login')}}"></script>
    </body>
</html>

resources/views/admin/master.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="title" content="{{env("PROJECT_NAME")}}">
        <title>@yield("title"){{env("PROJECT_NAME")}}</title>       
        <link rel="shortcut icon" href="img/favicon_1.ico">
        <!-- Google-Fonts -->
        <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:100,300,400,600,700,900,400italic' rel='stylesheet'>

        <!-- Bootstrap core CSS -->
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.bootstrap')}}" />
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.bootstrap-reset')}}" />

        <!--Animation css-->
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.animate')}}" />

        <!--Icon-fonts css-->
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.ionicons')}}" />
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.fontawesome')}}" />

        <!-- Custom styles for this template -->
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.style')}}" />
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.styleresponsive')}}" />
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.helper')}}" />
        
        <!-- Tostr Notification-->
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.toastr')}}" />

        <!-- sweet alerts -->
        <link  rel="stylesheet" type="text/css" href="{{config('admin_constant.css.sweetalert')}}" />

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
        <!--[if lt IE 9]>
          <script src="resources/assets/admin/js/html5shiv.js"></script>
          <script src="resources/assets/admin/js/respond.min.js"></script>
        <![endif]-->
        @yield('css')
        
    </head>
    <body>
        @include('admin.sidebar')
        <!--Main Content Start -->
        <section class="content">
            @include('admin.topnav')
            <!-- Page Content Start -->
                @yield("content")
            <!-- Page Content Ends -->
            <!-- Footer Start -->
            <footer class="footer">
                © {{date("Y")}}, <a href="{{url('/')}}">PerksVilla</a>, All rights reserved
            </footer>
            <!-- Footer Ends -->
        </section>
        <script>
            var baseURL = "{{url('/').'/'}}";
            var _token = "{{csrf_token()}}";
            var logoutUrl = "{{route('logout')}}";
        </script>
        <script type="text/javascript" src="{{config('admin_constant.script.jquery')}}"></script>
        <script type="text/javascript" src="{{config('admin_constant.script.bootstrap')}}"></script>
        <script type="text/javascript" src="{{config('admin_constant.script.modernizr')}}"></script>
        <script type="text/javascript" src="{{config('admin_constant.script.pace')}}"></script>
        <script type="text/javascript" src="{{config('admin_constant.script.wow')}}"></script>
        <script type="text/javascript" src="{{config('admin_constant.script.scrollto')}}"></script>
        <script type="text/javascript" src="{{config('admin_constant.script.nicescroll')}}"></script>
        <script type="text/javascript" src="{{config('admin_constant.script.moment')}}"></script>
        <script type="text/javascript" src="{{config('brand_constant.script.validate')}}"></script>
        <!-- Counter-up -->
        <script type='text/javascript' src="{{config('admin_constant.script.waypoints')}}"></script>
        <script type='text/javascript' src="{{config('admin_constant.script.counterup')}}"></script>

        <!-- EASY PIE CHART JS -->
        <script type='text/javascript' src="{{config('admin_constant.script.easypiechart')}}"></script>
        <script type='text/javascript' src="{{config('admin_constant.script.jqueryeasypiechart')}}"></script>
        <script type='text/javascript' src="{{config('admin_constant.script.example')}}"></script>

        <!-- sparkline -->
        <script type='text/javascript' src="{{config('admin_constant.script.sparkline')}}"></script>
        <script type='text/javascript' src="{{config('admin_constant.script.chartsparkline')}}"></script> 

        <!-- sweet alerts -->
        <script type='text/javascript' src="{{config('admin_constant.script.sweetalert')}}"></script>
        <script type='text/javascript' src="{{config('admin_constant.script.sweetalertinit')}}"></script> 

        <!-- Chat -->
        <script type='text/javascript' src="{{config('admin_constant.script.app')}}"></script>
        <script type='text/javascript' src="{{config('admin_constant.script.chat')}}"></script>

        <!-- Todo -->
        <script type='text/javascript' src="{{config('admin_constant.script.todo')}}"></script>
        
        <script type="text/javascript" src="{{config('admin_constant.script.knockout')}}"></script>
        <script type="text/javascript" src="{{config('admin_constant.script.toastr')}}"></script>
        <script type="text/javascript" src="{{config('constant.script.common.jquerymd5')}}"></script>
        <script type="text/javascript" src="{{config('constant.script.common.helper')}}"></script>
        <script type="text/javascript" src="{{config('constant.script.common.moment')}}"></script>

        <script>
        /* ==============================================
             Counter Up
             =============================================== */
            jQuery(document).ready(function($) {
                $('.counter').counterUp({
                    delay: 100,
                    time: 1200
                });
            });
            var static_image ="NoLogo.png";
        </script>
        @yield("script")
    </body>
</html>